### ISSUE TITLE
Maybe we should remove wayland and x11 compile flag

### ISSUE THREAD

**Issue by wrvsrx** [Icelk/clipcat#15]
Now the program can judge them at runtime.

**Comment by Icelk** [comment]
Instill think we should keep them in case somebody wants to build a wayland system without any x11. Since you cloned the x11 clipboard system, are all the dependencies required to build? If not, I might consider it :)

**Comment by wrvsrx** [comment]
Because these flags mess up build and code, and make test hard. Here are two bugs caused by that:

1. It seems that CI config is wrong now since it doesn't disable "all-backends" feature when build X11 version and wayland version.
2. https://github.com/Icelk/clipcat/blob/19d9708cdcfcb69d4a01e0576c554e9e1a73f9b9/src/manager.rs#L204-L250 code here only builds for wayland even when "all-backends" feature is enabled.

Besides, when distributing the program, I think distributing the binary with "all-backends" is more convenient and building with only wayland support is rarely needed.

**Comment by Icelk** [comment]
You've brought up some faults in my sloppy code. I'll have to be more deliberate in the future. Thank you.

I do however still see building without x11 as very alluring. I don't suppose there are many wayland-only clipboard managers (for the future) with the relative maturity of clipcat.
You're correct about distribution. But that doesn't conflict with custom-building with wayland-only. I'm willing to maintain the extra burden, and make sure that x11 doesn't break.

Regarding tests: do you imply future testing? Because I don't see any test code which interacts with the system (x11 or wayland compositor)

**Comment by Icelk** [comment]
Your concerns regarding CI and the paste issue are (hopefully) resolved with the latest commit.

**Comment by Icelk** [comment]
It's also worth noting I've done loads of #[cfg] before - icelk/kvarn uses this to a great extent.
Tests work flawlessly

**Comment by wrvsrx** [comment]
I agree with your opinion.
